[green_agent]
endpoint = "http://127.0.0.1:9039"
cmd = "python evaluator_proxy.py --host 127.0.0.1 --port 9039"

[[participants]]
role = "rita"
endpoint = "http://127.0.0.1:9044"
cmd = "python question_dummy_agent.py --host 127.0.0.1 --port 9044"

[config]
"list1_path" = "data/List1_FINAL_stimuli_list.csv"
"list2_path" = "data/List2_FINAL_stimuli_list.csv"
